### ISSUE TITLE
Potential mistake on the list of providers on Autocomplete+ wiki

### ISSUE THREAD

**Issue by yihangho** [steelbrain/autocomplete-hack#10]
The [Autocomplete+ wiki](https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers) says that this plugin is the provider of C++ (as well as PHP, but there's no mention of HackLang). I believe this is not true, but just want to be sure before editing the wiki. Am I right?

**Comment by steelbrain** [comment]
Fixed.
