### ISSUE TITLE
Describe in Readme what languages you provide suggestions for

### ISSUE THREAD

**Issue by rugk** [steelbrain/autocomplete-hack#15]
You seems to support multiple languages.
So you can use [this wiki page](https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers) to get out what languages you support, but it would be nice if you just list is in your Readme too.

**Comment by steelbrain** [comment]
This autocompletion package is actually for HackLang :) Just like the wiki page says. I have specified 3 languages (C++, Hack and PHP) because if the `language-hack` package is not installed, Atom detects the file as `C++` or `PHP`

**Comment by rugk** [comment]
Ah this is a bit confusing. Maybe a note should be added to the wiki page to show this.
