### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by girvo** [steelbrain/autocomplete-hack#7]
Hey there, lovely work on this plugin.

Supporting SSH is brilliant, and to be honest is basically sufficient even for a Docker container, but one thing I'd love to see is the ability to support Docker containers through `docker exec` or something similar. Of course, that would require project specific config, but as the SSH ability requires the same that shouldn't be much of a drama.

I've written a couple of bash scripts that leverage `docker exec` to run the type checker, so if there's a need for help with that feel free to let me know. 

Cheers,
Josh

**Comment by steelbrain** [comment]
Thanks for the idea, I am sure it won't be difficult at all to allow the user to add the command to be executed.

**Comment by steelbrain** [comment]
Fixed in the latest release
